name: Continuous Integration

on:
  push:
    paths-ignore:
      - "**/README.md"
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  rust-checks:
    name: Rust Checks
    runs-on: ubuntu-latest
    env:
      PHOTO_API_KEY: "NOT_SET"
      PHOTO_API_URL: "http://localhost:1234"
    strategy:
      fail-fast: false
      matrix:
        action:
          - command: fmt
            args: --all -- --check
          - command: clippy
            args: --all-features --workspace -- -D warnings
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Run command
        run: cargo ${{ matrix.action.command }} ${{ matrix.action.args }}

  rust-build:
    name: Rust Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Run command
        run: cargo build --release
      - uses: actions/upload-artifact@v4
        with:
          name: framer
          path: target/release/framer
